### ISSUE TITLE
Finish Ansible Playbook pre Bootstrap

### ISSUE THREAD

**Issue by marvin-steinke** [AurelWeinhold/calm#27]
A draft was already commited and needs to be finished for proper deployment and to enable remote working

**Comment by AurelWeinhold** [comment]
I think it's only missing escalation of privileges.

**Comment by lierseleow** [comment]
I changed the hosts filter to baremetal, so that the playbook hits all machines on which we deploy.

I also removed the virtualenv path, because this will be installed on bootstrap (also the path was not used by all machines).
If this becomes problematic we could add virtual env installation to prebootstrap.
EDIT: It IS problematic, this means we might want to investigate to add virtual env installation to the prebootstrap playbook or use the playbook AFTER bootstrap
EDIT2: It may not be problematic after all, the become=yes needed to be moved into the apt task. There is still another problem...

We may want to add the latest filter to the apt-package and docker installation. This would prevent that old installation are kept.
